version: '3.9'

services:
  stakeholders-migration:
    build:
      context: ./stakeholders-service
      dockerfile: Dockerfile
      target: execute-migration
    networks:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DATABASE_HOST=stakeholders-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=super
      - DATABASE_USER=postgres
      - DATABASE_SCHEMA=stakeholdersdb

  
  tours-migration:
    build:
      context: .                       
      dockerfile: ./tours-service/Dockerfile
      target: execute-migration
    networks:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DATABASE_HOST=tours-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=super
      - DATABASE_USER=postgres
      - DATABASE_SCHEMA=toursdb

  payments-migration:
    build:
      context: ./payments-service
      dockerfile: Dockerfile
      target: execute-migration
    networks:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DATABASE_HOST=payments-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=super
      - DATABASE_USER=postgres
      - DATABASE_SCHEMA=paymentsdb

networks:
  database:
     name: database
     driver: bridge
     external: true
