version: '3.9'

services:
  stakeholders-migration:
    build:
      context: ./stakeholders-service
      dockerfile: Dockerfile
      target: execute-migration
    depends_on:
      - stakeholders-db
    networks:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DATABASE_HOST=stakeholders-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=super
      - DATABASE_USER=postgres
      - DATABASE_SCHEMA=stakeholdersdb

  # database:
  #   image: postgres:13
  #   restart: always
  #   networks:
  #     - database
  #   environment:
  #     POSTGRES_PASSWORD: super
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: stakeholdersdb
  #   volumes:
  #     - type: volume
  #       source: stakeholdersdb
  #       target: /var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   stakeholdersdb:
#     name: stakeholdersdb

networks:
  database:
     name: database
     driver: bridge
     external: true
