global:
  scrape_interval: 5s

scrape_configs:
  - job_name: windows
    static_configs:
      - targets: ['host.docker.internal:9182']  # windows_exporter

  - job_name: docker-engine
    static_configs:
      - targets: ['host.docker.internal:9323']  # Docker daemon metrics

  - job_name: cadvisor
    static_configs:
      - targets: ["host.docker.internal:8084"]

    # ako Prometheus i Telegraf dele docker mre≈æu
  - job_name: 'telegraf'
    static_configs:
      - targets: ['host.docker.internal:9273']  # alternativa preko host porta